### ISSUE TITLE
sub sample循环如何设置才能保证一次收到一条消息？

### ISSUE THREAD

**Issue by muyufan** [emqtt/mqtt-jmeter#10]
我这边目前设置500ms，现在压力不大，但是还是有一次收到多条的情况

```
grep "Received 2 of message" result.jtl |wc -l 
258
```

因为我是用Switch Controller根据收到的消息类型来发送pub sample，在sub sample循环的时候，如果刚好收到一条消息，那么从response body提取到是什么类型的消息，然后执行pub sample

循环间隔可以再小点解决问题，但是太小了有大量的循环，会不会影响jmeter执行效率

**Comment by muyufan** [comment]
我现在不确定，在某一次sub sample循环 如果收到多条消息，response body值内容是啥，array？还是两条消息内容连接成一个string，我得去debug看看

**Comment by jinfahua** [comment]
目前sub sampler无法精确控制只收一条消息。

如果收到多条消息，多条消息内容连接成一个string，消息之间以“回车符”间隔。

**Comment by jinfahua** [comment]
如果想支持该功能，你想在sub sampler里如何使用该功能？界面里该如何支持？

**Comment by muyufan** [comment]
我就是按你在issue:10这里  #10 建议的用法，但是有时候subsample的response收到多条，就没有从response data获取到消息类型，下面的switch也就没能执行

**Comment by muyufan** [comment]
也许可以收到多条后，把那些switch contrler都包含到一个循环里？ 循环的次数就是收到的条数

**Comment by jinfahua** [comment]
做了一个新的branch - “exactOne”，你可以把代码checkout出来自己做个build试试看，如有问题再告知。

加了如下所示的一个控制 - 每个抽样收到的消息条数：缺省是-1，这种方式下跟原来的方式一样，每次sample里收到的消息是自上次之后收到的所有消息条数；如果输入大于0的值n，表示只有等到了n条消息的时候才会产生一个sample。如果输入的是0，则强制被转化成1. 

请注意：如果一直接收不到指定条数的消息，该虚拟用户线程会一直处于等待状态。

<img width="878" alt="Control received message" src="https://cloud.githubusercontent.com/assets/8246540/24576973/f824c3d2-16f7-11e7-8250-f9bfa77ee5d1.png">

**Comment by jinfahua** [comment]
Already supported and close the issue.
