### ISSUE TITLE
Sub Sampler 我已经添加了，但是在什么地方可以看到订阅的消息。

### ISSUE THREAD

**Issue by god-pane** [emqtt/mqtt-jmeter#12]
我这边需要根据订阅的消息，来发布不同的消息内容。

**Comment by jinfahua** [comment]
Please refer to comment https://github.com/emqtt/mqtt-jmeter/issues/5#issuecomment-284728419 for similar question. 

Also, we're developing a new feature to control the received message precisely which was mentioned in https://github.com/emqtt/mqtt-jmeter/issues/10 . E.g, sub sampler will be produced on receiving x (x can be configured to 1 ~ n) of message. The feature is still under testing. To try it, you can checkout code from timer_sub branch, and build the JAR by yourself.

**Comment by god-pane** [comment]
![image](https://cloud.githubusercontent.com/assets/9427959/25472879/c8312842-2b5f-11e7-806b-f8f7af5ae5cf.png)
我要模拟即连即挺的情况，是将Connection keep time 参数设置为0吗？ 关闭脚步就停止发包，下线了。

**Comment by jinfahua** [comment]
Connection sampler主要用于模拟背景连接，除了ping包不发送任何别的数据。如果模拟即连即停，不发送数据的话，可以按照你说的这样做。不知道这是模拟的什么样的场景？

**Comment by rende2005** [comment]
按照目前的实现方式，Connection keep time设置0，就是连接建立后立即正常disconnect，这样就没有机会发ping包了。你可以看到sampler很快执行完(连接建立的花费时间其实很短)。

在Connection keep time != 0的情况下，如果你在GUI里点击stop按钮来停止脚本，插件会感知到并主动disconnect再结束执行; 如果以其它方式强行关闭脚本，可能要依靠服务器端感知客户端断连并清理，问题也不大。

**Comment by god-pane** [comment]
这个地方默认是1800s 即30分钟， keep alive默认为300s 即5分钟， 我正常连接成功后，停止脚本，但是心跳包根本没有停止发送，还是每隔5分钟发一次，导致我再次开启脚步来连接时，不能连接成功，提示连接已存在了。我只能关闭jmeter来解决这个问题。

**Comment by rende2005** [comment]
你是怎么停止脚本的？你说的情况好像连接并没有断开，可以设法从server端查看连接状况确认一下。

**Comment by god-pane** [comment]
![image](https://cloud.githubusercontent.com/assets/9427959/25512226/b1868732-2bfe-11e7-8709-60e7ec429df7.png)  查看了的哈， 确认没有断开，还有心跳包。

**Comment by god-pane** [comment]
该问题是 开始脚本（正常建立连接）， 然后再停止脚本，多重复了几次，就出现。

**Comment by rende2005** [comment]
我确认一下：你现在是用的缺省的keep time=1800s, keep alive=300s? 然后GUI上点开始、结束，重复几次就有没断开的连接，是吧？

我们可能需要查看一下jmeter.log, 看disconnect是不是没有做成功。

另外，如果你不关心保持背景连接，即连即停，用keep time=0有什么问题吗? 为什么要手工停止脚本运行。你的测试场景我们不是特别明白。

**Comment by god-pane** [comment]
keep time=0，没有问题，是即连即停。 手工停止脚本只是在做测试。
符合我这边最终场景是：客户端上线后，先publish，然后subscribe，再根据subscribe返回不同的信息publish，然后我还要操作一些http请求，验证客户端的publish信息。

**Comment by rende2005** [comment]
了解。subscribe时选取合适的采样退出条件(可能是按收到的消息数=1），再分析返回的消息，做下一步的publish就可以了。

**Comment by god-pane** [comment]
还有在循环控制器下面先Connection Sampler，然后再添加一个pub Sampler， 我发现连接成功后，pub Sampler根本没有执行

**Comment by rende2005** [comment]
pub和sub里面都隐含了建立连接的过程，你不需要在pub前面放一个Connection Sampler.

Connection Sampler是用于构造背景长连接，你要是需要，可以把connection sampler放到一个单独的thread group里面。

**Comment by god-pane** [comment]
明白了

**Comment by god-pane** [comment]
谢谢
