### ISSUE TITLE
All results are not available for MQTT pub sampler in "View Results in Table"

### ISSUE THREAD

**Issue by shankybnl** [emqtt/mqtt-jmeter#14]
Hi,

I am not able to see all the result values for MQTT publisher sampler (latency, connect time, sample time and sent bytes). Please let me know how can I get these values?

![resutls](https://cloud.githubusercontent.com/assets/11002110/25950046/4e683e10-3677-11e7-83b6-d555aa068f5d.png)

Thanks in advance.

Regards,
Shanky

**Comment by jinfahua** [comment]
Now they are added except the connection time (the mqtt connection only created for once, so it will not be displayed here).
