### ISSUE TITLE
MQTT Sub Sampler Avg, Median, Max and Min times not visible in Aggregate Report

### ISSUE THREAD

**Issue by navneetkrishnam** [emqtt/mqtt-jmeter#15]
Hi. I see only 0 in all of Average, Median, Min and Max times in Aggregate Report.

**Comment by jinfahua** [comment]
did u select "timestamp" checkbox in both pub and sub sampler?

**Comment by navneetkrishnam** [comment]
Yes I have tried both by checking and unchecking the "timestamp" checkbox. I am using only the sub sampler. For publishing I am using MQTT lens.

**Comment by jinfahua** [comment]
The sub sample time (also called 'message latency time') can only be calculated correctly when it work together with pub samplers with 'Add timestamp in payload' checkbox selected. Please search 'message_latency' in https://github.com/emqtt/mqtt-jmeter for more detailed info.

**Comment by jinfahua** [comment]
Work as designed, and close the issue.
