### ISSUE TITLE
下载的jar包放在apache-jmeter中的ext下，重启没有sample

### ISSUE THREAD

**Issue by promission** [emqtt/mqtt-jmeter#17]
你好，我的apache-jmeter3.1和3.2版都下了一个。插件的jar是在这里下载的最新的，放到ext下面，重启没有看到sample，能帮忙排除下原因吗？

**Comment by rende2005** [comment]
你好，
能列一下<jmeter_home/lib/ext目录的内容及文件大小吗？
还有，你添加sampler时右键菜单的截图发过来看看？

**Comment by promission** [comment]
hello，https://github.com/promission/picture，大小和内容以及jmeter界面的截图在这里。

**Comment by promission** [comment]
@rende2005  help me，thanks

**Comment by rende2005** [comment]
Basically in the JMeter test script, you need to firstly create a "thread group", under which you define your various samplers, e.g. MQTT Pub/Sub Sampler. 

Your reply gives me the impression that you were looking for samplers at the "test plan" level, which is obviously incorrect. 

Please refer to the attached screenshot:
<img width="804" alt="jm" src="https://user-images.githubusercontent.com/10943265/28499491-f30b0456-6fe9-11e7-9066-ed5e492187b9.png">

**Comment by rende2005** [comment]
Please let me know if it's not an issue for you any more, then I'll close it.

**Comment by promission** [comment]
closed， thank you！
