### ISSUE TITLE
Unable to load topic on each iteration from csv file

### ISSUE THREAD

**Issue by Hiteshkikani** [emqtt/mqtt-jmeter#22]
Hi,

I have created a script using MQTT plug in which sends messages to a topic.
I have parameterized payload and passing message from csv file.
Jmeter is able to load new message from csv file on each iteration  and publish to the topic which is hard coded.
But when I try to parameterise Topic name and pass it from csv file, topic name is loaded only once when thread is actually started and is unable to update topic name on each iteration which is my  requirement.

**Comment by jinfahua** [comment]
Pub sampler could be parameterized,  but sub sampler cannot be parameterized - one sub sampler can only sub to one topic. If you'd like to have one user sub to different topics, now you will have to create several sub samplers.

**Comment by Hiteshkikani** [comment]
Thanks for reply.
I have already parameterized pub topic but the problem is topic not getting updated on each iteration. It loads value from csv only once and uses the same value throughout the test execution. I want pub topic to get updated on each iteration

**Comment by jinfahua** [comment]
I created a temp fix, please try following attachment. If it works for you, we'll include in the future release.

[mqtt-xmeter-jar-with-dependencies.jar.zip](https://github.com/emqtt/mqtt-jmeter/files/1340840/mqtt-xmeter-jar-with-dependencies.jar.zip)

**Comment by Hiteshkikani** [comment]
It is working now. 
Thanks.

**Comment by Hiteshkikani** [comment]
Hi,
The problem is same as mentioned in the  conversation above but this time it is with clientid. MQTT pub and sub sampler reads cliendId from a csv file only during 1st cycle (iteration) and then keeps same value for all following iterations during thread execution.
![image](https://user-images.githubusercontent.com/7577959/34662377-c6ce3bb2-f458-11e7-9ef3-08252d64149e.png)

My requirement is, the value of ${clientid} (in above picture) should be updated on all successive iterations. i.e. sampler should read new value from a file for every iteration.

Can you fix this problem?

P.S: I am re-opening same issue (#22) as the problem is quite similar to the  issue #22 :)

**Comment by Hiteshkikani** [comment]
otherwise it would be good idea and easier if you can add clear connection feature in the plugin

**Comment by rende2005** [comment]
@Hiteshkikani  ClientId (as part of MQTT context) is determined during the connection phase,  thus across the iterations within a JMeter thread, ClientId will not change.

We have a new implementation(in "separate_conn" branch ) to create MQTT connection before publish/subscribe sampler,  so it's promising you can clear the connection at the end of your iteration, and create a new one with another ClientId for the next loop. 

I will keep you posted after some verification test.

**Comment by rende2005** [comment]
@Hiteshkikani 
You can get the new plugin binary from https://github.com/emqtt/mqtt-jmeter/releases/tag/v1.0.1
Please refer to README instructions @ https://github.com/emqtt/mqtt-jmeter/commits/separate_conn when you try it out. 

Please let us know if this helps.

**Comment by Hiteshkikani** [comment]
@rende2005  thank you so much. This served my purpose. Appreciate your support
