### ISSUE TITLE
连接是发布和订阅消息的基础

### ISSUE THREAD

**Issue by god-pane** [emqtt/mqtt-jmeter#25]
在现有的插件中， 发布消息或者订阅消息是包含了连接操作， 能否做到先是连接操作，然后才是发布或者订阅消息， 可参考mqttfx客户端。

**Comment by jinfahua** [comment]
是的，我们在考虑是否更改成你建议的这种实现方式。

**Comment by rende2005** [comment]
@god-pane 
Please try out https://github.com/emqtt/mqtt-jmeter/releases/tag/v1.0.1

**Comment by god-pane** [comment]
使用一个循环控制器， 创建多个连接，只能有一个连接成功

**Comment by rende2005** [comment]
是这样的。现在的实现就是每一个线程对应一个服务器连接，在连接已存在的情况试图再次建立连接是不成功的（除非它调用DisConnect后再次发起连接）。如果你需要测试多个并发的连接，可以调整脚本结构，比如使用常规的线程组模拟多个并发用户。

**Comment by jinfahua** [comment]
It's supported and close the issue.
