### ISSUE TITLE
WSS Support?

### ISSUE THREAD

**Issue by kdthomas2121** [emqtt/mqtt-jmeter#27]
Trying to load test my IOT MQTT , but from what I can tell this plugin doesn't support WSS? Also I have a host name and then a path, should it work just inputting the entire URL into server name? 

Thanks for this!

**Comment by jinfahua** [comment]
Secured web socket is not supported. Currently the plugin support general TCP, and also the SSL socket connection.

**Comment by jinfahua** [comment]
You can use this plugin to test the websocket - https://github.com/maciejzaleski/JMeter-WebSocketSampler/issues

**Comment by jinfahua** [comment]
Close the issue.
