### ISSUE TITLE
Dual SSL authentication - password fields are reversed

### ISSUE THREAD

**Issue by Hmm90** [emqtt/mqtt-jmeter#29]
Used mqtt-xmeter-jar-with-dependencies.jar.zip in verion 1.0.

And try to connected so ssl mqtt broker by Dual SSL authentication and got errors that password of truststore is wrong. 
Note: My Trust Key Store and Client Certificate have different password. After tying hours and suddenly found out that the password fields are reversed.  Secret beside Trust Key Store is the secret for the Client Certificate and the secret beside Client Certificate is the password for the Trust Key Store.

Greetings

**Comment by rende2005** [comment]
Hi @Hmm90 
Thanks for the bug report and issue probing!  Sorry about the glitch.

The fix is delivered and you can download the updated jar file in release 1.0 page. Please feel free to give it a try.

**Comment by Hmm90** [comment]
having problems with the fix it seem that the password fields are flipping  back and forth when activating the step (klick on it). 
The position of the password field were not fix. Can't use the fixed version and uses still the old one,

**Comment by rende2005** [comment]
@Hmm90 You're right, there's still issue in the previous fix. Would you please try the updated jar in the release 1.0 page?

**Comment by rende2005** [comment]
mqtt-xmeter-jar-with-dependencies.jar  (filesize: 462879 Bytes)

**Comment by Hmm90** [comment]
it is working for me
