### ISSUE TITLE
host null and port out of range exception

### ISSUE THREAD

**Issue by ajaycsse** [emqtt/mqtt-jmeter#3]
I am trying to use the MQTT Pub Sampler with the below options:
Server name or IP: something(my server hostname)
port number: 8883
protocols: SSL - Dual SSL Authentication( I have the jks and p12 cert's with secret)
user name and password - we dont use username/password we only use cert's
client id prefix -  something(my client id)
QoS level - 0
Topic name: something/something
payload: some string

When I try to use the mqtt pub sampler with above parameters I am getting below error.
I am getting below error:
2017/02/23 10:37:53 INFO  - jmeter.engine.StandardJMeterEngine: Running the test! 
2017/02/23 10:37:53 INFO  - jmeter.samplers.SampleEvent: List of sample_variables: [] 
2017/02/23 10:37:53 INFO  - jmeter.gui.util.JMeterMenuBar: setRunning(true,*local*) 
2017/02/23 10:37:53 INFO  - jmeter.engine.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group 
2017/02/23 10:37:53 INFO  - jmeter.engine.StandardJMeterEngine: Starting 1 threads for group Thread Group. 
2017/02/23 10:37:53 INFO  - jmeter.engine.StandardJMeterEngine: Thread will continue on error 
2017/02/23 10:37:53 INFO  - jmeter.threads.ThreadGroup: Starting thread group number 1 threads 1 ramp-up 1 perThread 1000.0 delayedStart=false 
2017/02/23 10:37:53 INFO  - jmeter.threads.ThreadGroup: Started thread group number 1 
2017/02/23 10:37:53 INFO  - jmeter.engine.StandardJMeterEngine: All thread groups have been started 
2017/02/23 10:37:53 INFO  - jmeter.threads.JMeterThread: Thread started: Thread Group 1-1 
2017/02/23 10:37:53 INFO  - net.xmeter.Util: Configured with dual SSL, trying to load key files. 
2017/02/23 10:37:53 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.IllegalArgumentException: hostname can't be null
	at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:216)
	at org.fusesource.hawtdispatch.transport.TcpTransport$2.run(TcpTransport.java:458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

But when I prefix this with ssl://my host name I get the below exception.
2017/02/23 10:38:29 INFO  - jmeter.threads.ThreadGroup: Started thread group number 1 
2017/02/23 10:38:29 INFO  - jmeter.engine.StandardJMeterEngine: All thread groups have been started 
2017/02/23 10:38:29 INFO  - jmeter.threads.JMeterThread: Thread started: Thread Group 1-1 
2017/02/23 10:38:29 INFO  - net.xmeter.Util: Configured with dual SSL, trying to load key files. 
2017/02/23 10:38:38 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.IllegalArgumentException: port out of range:-1
	at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:224)
	at org.fusesource.hawtdispatch.transport.TcpTransport$2.run(TcpTransport.java:458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Could you kindly suggest me what could go wrong here or did I provide in wrong format.

**Comment by jinfahua** [comment]
How about change it to IP address instead of host name?

**Comment by jinfahua** [comment]
Also, do not add protocols ahead of host name, protocol is set in "Protocols" dropdown box.

**Comment by rende2005** [comment]
@ajaycsse  if using hostname, please ensure it can be resolved to the desired IP address (from the machine where you run this plugin),  and also avoid special characters such as '_' in hostname.

**Comment by jinfahua** [comment]
Close the issue, and feel free to reopen it if it still has problems.
