### ISSUE TITLE
可以把pub sample和sub sample做成一个sample吗？

### ISSUE THREAD

**Issue by redbiscuit** [emqtt/mqtt-jmeter#38]
就做成一个类似http的请求和响应接收，比如我要先pub到mqtt服务器，然后mqtt服务器马上会返回一个响应。
目前是分开的 导致pub后服务器传回来的消息不能迅速被接收到。

**Comment by jinfahua** [comment]
MQTT的sub协议是异步的，不像HTTP是同步的协议，这个功能不适用于MQTT。
