### ISSUE TITLE
PubSampler does not re-connect when server returns SERVER_UNAVAILABLE while login

### ISSUE THREAD

**Issue by DanielMaier-BSI** [emqtt/mqtt-jmeter#41]
Hi,
the plugin does not re-connect when server returns SERVER_UNAVAILABLE while login even when connect attempts are set to -1. This leads to failing samples on each invocation as PubSampler fails all results when connection is not ready.

The root cause is in underlying MQTT client: https://github.com/fusesource/mqtt-client/blob/1c8a86a9e678b9a71481116e1e294125616482f3/mqtt-client/src/main/java/org/fusesource/mqtt/client/CallbackConnection.java#L360

Do you see any chance to get this fixed within the jmeter plugin as the MQTT client project seems to be dead or do you have any plans to switch or fork the underlying MQTT client?

Many thanks
Daniel

**Comment by jinfahua** [comment]
So is it OK for PubSampler stop running when connection is not ready?

**Comment by DanielMaier-BSI** [comment]
What exactly means "stop running"?

Background: We test a MQTT server that responds under pressure with SERVER_UNAVAILABLE on connection establishment. Would be great if our jmeter scenario just tries to re-connect and recovers over time.

**Comment by jinfahua** [comment]
Normally, if the MQTT server reaches max capacity, it does not make sense to keep re-connecting to server if your purpose is to evaluate the server's capacity before you optimize MQTT server.

Refer to below for 'stop running' - it's a setting of threadgroup, when the thread find any error, then the current thread would be stop running (not test).

<img width="1120" alt="thread-group-setting" src="https://user-images.githubusercontent.com/8246540/44152798-023d1c18-a0d9-11e8-8574-2371e3f717e6.png">

**Comment by DanielMaier-BSI** [comment]
Well the max capacity of the server is not reached. Server only is not able to handle so many concurrent connection establishments. Perhaps increasing ramp-up period is a proper way to solve my issue. 

Thanks for the hint with stop thread, will use it for another test scenario :).

However this server also returns SERVER_UNAVAILABLE when it cannot reach one of it's dependent systems at any time. I am not sure if it is worth to implement re-connect for this exceptional case, what do you think? At least re-connect is implemented for network related exceptions.

Do you know how PubSampler behaves when server just closes the connection within the test scenario, does it re-connect?

What are your future plans with this plugin, do you plan to stay with this MQTT client? Do you know if the MQTT client project is dead (last activity more than 2 years ago)?

**Comment by jinfahua** [comment]
Did you set "Reconnect attempt max" or "Connect attempt max" to -1. When a connection was already established, I think 'Reconnect attempt' would be made, but not 'Connect attempt'. The 'Connect attempt'  will be only execute for the first time.

Yes, we have plan to switch the underlying MQTT client - maybe use (Paho Java client)[https://github.com/eclipse/paho.mqtt.java], seems Paho is more active.

**Comment by DanielMaier-BSI** [comment]
I set both to "-1". I solved my issue by increasing the ramp-up period. Thanks for your hints.

I consider the fact that this MQTT client does not re-connect initially when server returns SERVER_UNAVAILABLE (which should be very rare when it is not caused by too much load) as a bug in the MQTT client. Glad to hear that you are planing to switch to a more active MQTT client project. So I don't think it is worthwhile to work around this issue inside the jmeter plugin.

**Comment by luolala07** [comment]
> I set both to "-1". I solved my issue by increasing the ramp-up period. Thanks for your hints.
> 
> I consider the fact that this MQTT client does not re-connect initially when server returns SERVER_UNAVAILABLE (which should be very rare when it is not caused by too much load) as a bug in the MQTT client. Glad to hear that you are planing to switch to a more active MQTT client project. So I don't think it is worthwhile to work around this issue inside the jmeter plugin.

Hi, Daniel

Nice to meet you. I'm Na. I also met this issue during a test. may I ask how you adjust the ramp up period? by which rate? I found that although the reconnect happened, it's pretty unstable and the client continues trying to connect in spite of an existing connection, which cause a lot of connections drops in the end. Look forward to hearing from you. 

Thanks and best regards,
Na.
