### ISSUE TITLE
订阅消息后，没有响应内容

### ISSUE THREAD

**Issue by fengzhen2009** [emqtt/mqtt-jmeter#42]
我订阅了消息后，但是响应内容那里却没有消息
![image](https://user-images.githubusercontent.com/18163842/44386438-14871380-a555-11e8-95ea-66b10db5873a.png)

![image](https://user-images.githubusercontent.com/18163842/44386363-e30e4800-a554-11e8-938e-1510a63a6b10.png)
![image](https://user-images.githubusercontent.com/18163842/44386384-edc8dd00-a554-11e8-9324-1299a8833c6d.png)
而我用mqtt.fx工具是可以收到订阅消息的，如下图：
![image](https://user-images.githubusercontent.com/18163842/44386485-397b8680-a555-11e8-97d5-7b32ea3c5b97.png)
有人告诉我，我这个是什么问题吗？

**Comment by fengzhen2009** [comment]
可以了，thanks

**Comment by fengzhen2009** [comment]
还有一个问题就是，我在线程组中一起跑发布消息跟订阅消息，如图：
![image](https://user-images.githubusercontent.com/18163842/44562754-ad07d880-a78d-11e8-87b1-9d396c142c8b.png)

当发布成功后，订阅的消息还是没有内容，这个要怎么解决
![image](https://user-images.githubusercontent.com/18163842/44562768-bd1fb800-a78d-11e8-8329-9bc4cd5a9c0f.png)
![image](https://user-images.githubusercontent.com/18163842/44562780-c741b680-a78d-11e8-829e-416aaf547a43.png)

**Comment by willdy** [comment]
我也遇到了同样的问题，jmeter是5.1的，Sub Sampler中勾选了“Debug response”，显示的是乱码，用MQTT工具显示是正常的，这是什么问题，怎么处理，谢谢
![QQ图片20191011113349](https://user-images.githubusercontent.com/56422237/66622692-43f65500-ec1b-11e9-9c71-c31b5100efaf.png)
![QQ图片20191011113238](https://user-images.githubusercontent.com/56422237/66622695-4789dc00-ec1b-11e9-8cad-311edd959a0f.png)

![QQ图片20191011113323](https://user-images.githubusercontent.com/56422237/66622698-49ec3600-ec1b-11e9-818d-f6fa23207573.png)
![QQ图片20191011113517](https://user-images.githubusercontent.com/56422237/66622705-4d7fbd00-ec1b-11e9-8bd5-2115c894ee82.png)
