### ISSUE TITLE
sub sample收到的数据如何保存为变量，然后在pub sample里引用？

### ISSUE THREAD

**Issue by muyufan** [emqtt/mqtt-jmeter#5]
就类似http sample，可以把http的响应保存到变量，然后后面的http sample继续用这个变量的内容

我看到目前sub sample有个debug response的选项可以把订阅topic里的收到的数据打印

**Comment by jinfahua** [comment]
可以使用Post Processor中的正则表达式抽取器抽取到变量就可以了

**Comment by jinfahua** [comment]
需要先勾上debug response，否则无法从“Response data“里抽取数据

**Comment by rende2005** [comment]
@muyufan Please let us know if PostProcessor approach works for you or not.

**Comment by muyufan** [comment]
已经勾选了，但是cmd窗口，查看结果树页面都没有消息，wireshark抓包显示publish完消息，客户端马上就关闭了连接，后台的消息还没来得及推送给客户端
![qq 20170308142229](https://cloud.githubusercontent.com/assets/92053/23692726/533ad6f8-040b-11e7-89df-7fb548403661.png)

**Comment by muyufan** [comment]
sub 和 pub sample 里 keep alive  我都设置的很长，但是点击jmeter start后 也还是没起作用

**Comment by jinfahua** [comment]
keep alive是设置发送ping包的频率，不是连接的时间长度。

Sub是异步接收消息的，如果在包含Sub的线程组中设置的运行次数只有一次，Pub端发送的消息在没有转发到Sub之前，Sub已经结束了，因此Sub无法接收到数据。方便的话，你可以描述一下你要实现的测试场景，一起看看如何设计脚本比较合适。

**Comment by muyufan** [comment]
很多物联网设备，后台服务启动之前会订阅topic：server

jmeter客户端sub sampe订阅它自己的专用topic：client/id
jmeter客户端pub 身份认证 消息到到topic：server，后台服务收到后发送token到主题：client/id

我期望jmeter客户端sub sample能够处理主题：client/id里的内容：
例如，如果主题里的内容是身份认证的回应，那么我在Post Processor里获取token后保存到变量；

所以我在想 设计一个if controller或者switch controller，判断sub sampe接收到的消息的内容
如果主题里的内容是业务命令A，那么我启动pub sample发送业务消息A
如果主题里的内容是业务命令B，那么我启动pub sample发送业务消息B

但是问题是sub sample是一次性的还是，实时的一直监听后台发到主题client/id的命令消息的？

**Comment by jinfahua** [comment]
<img width="266" alt="screen shot 2017-03-08 at 4 19 02 pm" src="https://cloud.githubusercontent.com/assets/8246540/23695602/039ad0ca-041b-11e7-8642-fb236f40c913.png">

你可以试试我建议的测试计划，如上图所示。

sub sampler的结果执行次数是根据现场组里的“Loop Count“决定的。建议把“Thread Group”中的Loop Count设置成为“Forever”，“MQTT Sub Sampler”下面加一个Constant Timer，Constant Timer可以设置睡眠时间，那么在此睡眠时间段内收到的消息都会显示在Response data中。然后根据抽取出的结果执行不同的pub。

**Comment by jinfahua** [comment]
Close the issue, and re-open it if still has problems.
