### ISSUE TITLE
ERROR - net.xmeter.samplers.PubSampler: Ping timeout java.net.ProtocolException: Ping timeout

### ISSUE THREAD

**Issue by muyufan** [emqtt/mqtt-jmeter#7]
> 2017/03/17 09:23:00 INFO  - jmeter.reporters.Summariser: summary +    150 in 00:00:30 =    5.0/s Avg:     4 Min:     0 Max:    11 Err:    18 (12.00%) Active: 50 Started: 50 Finished: 0 
2017/03/17 09:23:00 INFO  - jmeter.reporters.Summariser: summary = 228482 in 12:43:33 =    5.0/s Avg:    18 Min:     0 Max: 527934 Err: 15480 (6.78%) 
2017/03/17 09:23:01 ERROR - net.xmeter.samplers.PubSampler: Ping timeout java.net.ProtocolException: Ping timeout
	at org.fusesource.mqtt.client.CallbackConnection$7$1.run(CallbackConnection.java:467)
	at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:100)
	at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77)

我看到CallbackConnection.java:467
> handleSessionFailure(new ProtocolException("Ping timeout").fillInStackTrace());

是不是意味着jmeter和mqtt的连接有问题，pub sample超时了？

**Comment by jinfahua** [comment]
应该是心跳包不能发送到服务器，超时了。

**Comment by muyufan** [comment]
谢谢。

我测了下pub sample，起了50个线程，每个线程每隔10秒上传一条消息，大概发了1晚上，有6个线程偶尔会有如下错误。

但并不是出错后这个线程后面一直出错，后面还是又继续正常发了，我猜测是不是出错时刻连接断掉了，然后线程会自动重连

跑了几个小时后result.jtl里出现的pub消息错误
elapsed字段520295就超时了，0.5秒？pub sample默认是0.5秒超时吗？

`timeStamp,elapsed,label,responseCode,responseMessage,threadName,dataType,success,failureMessage,bytes,sentBytes,grpThreads,allThreads,Latency,IdleTime,Connect`
`1489685474534,520295,测试消息,500,Connection org.fusesource.mqtt.client.FutureConnection@588972e1 connected failed.,场景1 1-28,,false,,7,0,50,50,0,0,0`

貌似又不是0.5秒超时，因为后面这个FutureConnection@588972e1出错是耗时很短，
`1489704005952,1,测试消息,500,Connection org.fusesource.mqtt.client.FutureConnection@588972e1 connected failed.,场景1 1-28,,false,,7,0,50,50,0,0,0
`

PubSampler.java里的代码，这里应该是写Publish failed吧？
`result.setResponseMessage(MessageFormat.format("Connection {0} connected failed.", connection));`

**Comment by jinfahua** [comment]
PubSampler中对发出去的消息会一直等待，不会有timeout这一说，除非是捕获了异常，你可以看看JMeter的日志里是否有别的异常。PubSampler中有一项配置是“Reconnect Attempt Max”，缺省值为0，意味着如果连接断开了，不会重新连接，具体也需要结合服务器端的日志进行分析。

PubSampler里的setResponseMessage方法已经改了，多谢提醒。

**Comment by muyufan** [comment]
谢谢，应该是网络问题，这几天测试没出现了，但是有新问题麻烦能看看吗

**Comment by muyufan** [comment]
sub sample在收到消息后，会马上断开连接，每次测试都是这样的现象

10.28.1.29是jmeter   mqtt-server是10.28.4.76

可以看到jmeter收到消息后主动reset了连接

![error](https://cloud.githubusercontent.com/assets/92053/24201870/5b85b43a-0f4c-11e7-8e28-477595bda056.png)

**Comment by muyufan** [comment]
问题找到了，我在sub sample代码里加入了收到消息后处理消息的代码，我这边是对二进制的消息payload做了解析操作，解析有问题的话就直接连接断开了

现在我把 catch IOException 改成了Exception，就没断开连接了，日志里也打印了具体我加入解析代码的出错信息

**Comment by jinfahua** [comment]
OK, glad to see the problem is solved, so close the issue.
