### ISSUE TITLE
Copy paste does not work.

### ISSUE THREAD

**Issue by Raul666** [emqtt/mqtt-jmeter#9]
Steps:
1. Copy a thread and paste it some where in test plan.
2. Or copy a MQTT PUB sampler and paste it in some other Thread. It shows the error:
"An Error occured while copying node: java.lang.Object"

**Comment by jinfahua** [comment]
Raul, the pub can be copied in my test, but the sub sampler has the problem. The issue has been fixed, and please download new binary from release page and try it again.

**Comment by jinfahua** [comment]
Download from this url - https://github.com/emqtt/mqtt-jmeter/releases/download/v0.91/mqtt-xmeter-jar-with-dependencies.jar.zip

**Comment by Raul666** [comment]
Solved. **TEST OK.**
FIXED. 
Tested with the jar provided for the other issue: CSV data config.
I can now copy paste Pub and sub both and others in Test plan.
thanks.

**Comment by jinfahua** [comment]
Thanks for your feedback. Close the issue.
